import sqlite3
import re
from ciscoconfparse import CiscoConfParse
from backend.PyCode.share.config import DB_TABLES, get_db_connection

# GỌI TÊN BẢNG NAT
T_NAT_MAIN = DB_TABLES["nat"]["main"]
T_NAT_INTF = DB_TABLES["nat"]["interfaces"]
T_NAT_POOL = DB_TABLES["nat"]["pools"]
T_NAT_STATIC = DB_TABLES["nat"]["static_mappings"]
T_NAT_OVERLOAD = DB_TABLES["nat"]["overload_rules"]
T_NAT_DYNAMIC = DB_TABLES["nat"]["dynamic_rules"]

# GỌI TÊN BẢNG ACL THƯỜNG VÀ NAT ACL
T_ACL_MAIN = DB_TABLES["acl"]["main"]
T_ACL_STD = DB_TABLES["acl"]["standard"]
T_ACL_EXT = DB_TABLES["acl"]["extended"]

T_NAT_ACL_MAIN = DB_TABLES["nat_acl"]["main"]
T_NAT_ACL_STD = DB_TABLES["nat_acl"]["standard"]
T_NAT_ACL_EXT = DB_TABLES["nat_acl"]["extended"]

def parse_static_nat(tokens):
    proto, l_ip, l_port, g_ip, g_port, extendable = "", "", "", "", "", 0
    if tokens and tokens[0] in ['tcp', 'udp']: proto = tokens.pop(0)
    l_ip = tokens.pop(0) if tokens else ""
    if proto and tokens and tokens[0].isdigit(): l_port = tokens.pop(0)
    g_ip = tokens.pop(0) if tokens else ""
    if proto and tokens and tokens[0].isdigit(): g_port = tokens.pop(0)
    if tokens and tokens[0] == "extendable": extendable = 1
    return {"protocol": proto, "local_ip": l_ip, "local_port": l_port, "global_ip": g_ip, "global_port": g_port, "extendable": extendable}

def sync_nat_worker(host_ip: str, parse_obj: CiscoConfParse, db_path: str):
    print(f"[INFO] Bắt đầu băm cấu hình NAT cho {host_ip}...")
    
    parsed_data = {"interfaces": [], "pools": [], "static": [], "dynamic_pool": [], "overload_intf": []}

    # =============================================================
    # BƯỚC 1: TRÍCH XUẤT (PARSING)
    # =============================================================
    for intf_obj in parse_obj.find_objects(r"^interface "):
        intf_name = intf_obj.text.split("interface ")[-1].strip()
        for nat_cmd in intf_obj.re_search_children(r"^\s+ip nat (inside|outside)"):
            role = "inside" if "inside" in nat_cmd.text else "outside"
            parsed_data["interfaces"].append({"name": intf_name, "role": role})

    for pool_obj in parse_obj.find_objects(r"^ip nat pool "):
        match = re.search(r"^ip nat pool (\S+) (\S+) (\S+) (netmask|prefix-length) (\S+)", pool_obj.text.strip())
        if match:
            p_name, start, end, mask_type, mask_val = match.groups()
            parsed_data["pools"].append({"name": p_name, "start": start, "end": end, "netmask": mask_val if mask_type == "netmask" else "", "prefix": mask_val if mask_type == "prefix-length" else ""})

    for rule_obj in parse_obj.find_objects(r"^ip nat inside source "):
        tokens = rule_obj.text.strip().split()[4:] 
        if not tokens: continue
        type_kw = tokens.pop(0)
        if type_kw == "static":
            parsed_data["static"].append(parse_static_nat(tokens))
        elif type_kw == "list":
            acl_name = tokens.pop(0) if tokens else ""
            target_type = tokens.pop(0) if tokens else "" 
            target_name = tokens.pop(0) if tokens else ""
            overload = 1 if tokens and tokens[0] == "overload" else 0
            
            if target_type == "pool": parsed_data["dynamic_pool"].append({"acl": acl_name, "pool": target_name, "overload": overload})
            elif target_type == "interface": parsed_data["overload_intf"].append({"acl": acl_name, "intf": target_name, "overload": overload})

    # GOM DANH SÁCH ACL ĐƯỢC NAT SỬ DỤNG
    used_acls = set([ov["acl"] for ov in parsed_data["overload_intf"]] + [dp["acl"] for dp in parsed_data["dynamic_pool"]])

    # =============================================================
    # BƯỚC 2: ĐỒNG BỘ VÀ PHÂN LOẠI ACL THÔNG MINH
    # =============================================================
    conn = get_db_connection()
    c = conn.cursor()
    
    try:
        has_nat_config = any(parsed_data.values())

        if not has_nat_config:
            c.execute(f"DELETE FROM {T_NAT_MAIN} WHERE host=?", (host_ip,))
            conn.commit()
            print(f"[+] NAT Worker: Router {host_ip} trắng trơn NAT, đã dọn sạch DB!")
            return 
            
        # 1. TÌM HOẶC TẠO NAT PROFILE
        c.execute(f"SELECT nat_id FROM {T_NAT_MAIN} WHERE host=?", (host_ip,))
        row = c.fetchone()
        if row:
            nat_id = row[0]
            c.execute(f"UPDATE {T_NAT_MAIN} SET success = 1 WHERE nat_id = ?", (nat_id,))
        else:
            c.execute(f"INSERT INTO {T_NAT_MAIN} (nat_name, nat_type, host, description, success, action_cfg) VALUES ('Global_NAT', 'static', ?, 'Auto-generated by Sync', 1, 1)", (host_ip,))
            nat_id = c.lastrowid

        # 2. XỬ LÝ "BẮT CÓC" ACL TỪ BẢNG THƯỜNG SANG BẢNG NAT
        for acl_name in used_acls:
            # Soi xem nó có đang nằm nhầm bên bảng ACL Thường do thằng sync_acl chèn vào không?
            c.execute(f"SELECT Acl_id, acl_type, description, action_Cfg FROM {T_ACL_MAIN} WHERE acl_name = ? AND host = ?", (acl_name, host_ip))
            wrong_acl = c.fetchone()
            
            if wrong_acl:
                old_id, acl_type, desc, act_cfg = wrong_acl
                
                # Bơm vỏ sang bảng NAT ACL
                c.execute(f"DELETE FROM {T_NAT_ACL_MAIN} WHERE acl_name = ? AND host = ?", (acl_name, host_ip))
                c.execute(f"INSERT INTO {T_NAT_ACL_MAIN} (acl_name, acl_type, host, description, success, action_Cfg) VALUES (?, ?, ?, ?, 1, ?)", (acl_name, acl_type, host_ip, desc, act_cfg))
                new_nat_id = c.lastrowid
                
                # Lấy lõi ruột chuyển sang bảng NAT
                if acl_type == 'standard':
                    c.execute(f"SELECT sequence, action, source, wildcard FROM {T_ACL_STD} WHERE acl_id = ?", (old_id,))
                    for r in c.fetchall():
                        c.execute(f"INSERT INTO {T_NAT_ACL_STD} (nat_acl_id, sequence, action, source, wildcard, success) VALUES (?, ?, ?, ?, ?, 1)", (new_nat_id, *r))
                    c.execute(f"DELETE FROM {T_ACL_STD} WHERE acl_id = ?", (old_id,))
                elif acl_type == 'extended':
                    c.execute(f"SELECT sequence, action, protocol, source, src_wildcard, src_port, destination, dst_wildcard, dst_port FROM {T_ACL_EXT} WHERE acl_id = ?", (old_id,))
                    for r in c.fetchall():
                        c.execute(f"INSERT INTO {T_NAT_ACL_EXT} (nat_acl_id, sequence, action, protocol, source, src_wildcard, src_port, destination, dst_wildcard, dst_port, success) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)", (new_nat_id, *r))
                    c.execute(f"DELETE FROM {T_ACL_EXT} WHERE acl_id = ?", (old_id,))
                    
                # xóa tàn dư bên bảng thường
                c.execute(f"DELETE FROM {T_ACL_MAIN} WHERE Acl_id = ?", (old_id,))
                print(f"[*] Đã nhận diện và di dời thành công ACL '{acl_name}' từ bảng Thường sang bảng NAT!")
            else:
                # Nếu không có ở bảng thường, check xem bảng NAT có sẵn chưa
                c.execute(f"SELECT nat_acl_id FROM {T_NAT_ACL_MAIN} WHERE acl_name = ? AND host = ?", (acl_name, host_ip))
                if not c.fetchone():
                    c.execute(f"INSERT INTO {T_NAT_ACL_MAIN} (acl_name, acl_type, host, description, success, action_Cfg) VALUES (?, 'standard', ?, 'Auto-generated Placeholder', 1, 1)", (acl_name, host_ip))
        # 2.5 DỌN DẸP ACL MỒ CÔI BÊN BẢNG NAT (TRẢ VỀ CHO ACL THƯỜNG)
        c.execute(f"SELECT acl_name FROM {T_NAT_ACL_MAIN} WHERE host = ?", (host_ip,))
        for row in c.fetchall():
            db_acl_name = row[0]
            if db_acl_name not in used_acls:
                # Nếu ACL trong DB NAT không còn nằm trong danh sách đang dùng -> Xóa!
                c.execute(f"DELETE FROM {T_NAT_ACL_MAIN} WHERE acl_name = ? AND host = ?", (db_acl_name, host_ip))
                print(f"[*] Đã dọn dẹp NAT ACL '{db_acl_name}' (Trả về làm ACL thường).")

        # 3. DỌN DẸP DỮ LIỆU NAT CŨ
        c.execute(f"DELETE FROM {T_NAT_INTF} WHERE nat_id=?", (nat_id,))
        c.execute(f"DELETE FROM {T_NAT_POOL} WHERE nat_id=?", (nat_id,))
        c.execute(f"DELETE FROM {T_NAT_STATIC} WHERE nat_id=?", (nat_id,))
        c.execute(f"DELETE FROM {T_NAT_OVERLOAD} WHERE nat_id=?", (nat_id,))

        # 4. BƠM DỮ LIỆU NAT MỚI
        for i in parsed_data["interfaces"]:
            c.execute(f"INSERT INTO {T_NAT_INTF} (nat_id, interface_name, nat_role, success) VALUES (?, ?, ?, 1)", (nat_id, i["name"], i["role"]))
        for p in parsed_data["pools"]:
            c.execute(f"INSERT INTO {T_NAT_POOL} (nat_id, pool_name, start_ip, end_ip, netmask, prefix_length, success) VALUES (?, ?, ?, ?, ?, ?, 1)", (nat_id, p["name"], p["start"], p["end"], p["netmask"], p["prefix"]))
        for s in parsed_data["static"]:
            c.execute(f"INSERT INTO {T_NAT_STATIC} (nat_id, inside_local_ip, inside_global_ip, protocol, local_port, global_port, is_extendable, success) VALUES (?, ?, ?, ?, ?, ?, ?, 1)", (nat_id, s["local_ip"], s["global_ip"], s["protocol"], s["local_port"], s["global_port"], s["extendable"]))

        # Bơm Rule Động & PAT (Gắn ID ACL chuẩn chỉnh)
        for ov in parsed_data["overload_intf"]:
            c.execute(f"SELECT nat_acl_id FROM {T_NAT_ACL_MAIN} WHERE acl_name = ? AND host = ?", (ov["acl"], host_ip))
            acl_row = c.fetchone()
            if acl_row: c.execute(f"INSERT INTO {T_NAT_OVERLOAD} (nat_id, nat_acl_id, outside_interface, overload, success) VALUES (?, ?, ?, ?, 1)", (nat_id, acl_row[0], ov["intf"], ov["overload"]))

        for dp in parsed_data["dynamic_pool"]:
             c.execute(f"SELECT pool_id FROM {T_NAT_POOL} WHERE pool_name = ? AND nat_id = ?", (dp["pool"], nat_id))
             p_row = c.fetchone()
             c.execute(f"SELECT nat_acl_id FROM {T_NAT_ACL_MAIN} WHERE acl_name = ? AND host = ?", (dp["acl"], host_ip))
             a_row = c.fetchone()
             if p_row and a_row: c.execute(f"INSERT INTO {T_NAT_DYNAMIC} (nat_id, nat_acl_id, pool_id, overload, success) VALUES (?, ?, ?, ?, 1)", (nat_id, a_row[0], p_row[0], dp["overload"]))

        conn.commit()
        print(f"[+] NAT Worker: Đồng bộ NAT thành công cho {host_ip}!")

    except Exception as e:
        print(f"[-] NAT Worker LỖI: {e}")
        conn.rollback()
    finally:
        conn.close()