from .process_compare import describe_process_submission, is_blank_ospf_process_submission, load_process_for_compare, sync_ospf_networks
from .process_store import archive_ospf_process, insert_ospf_process
